version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "weekly"
    time: "07:00"
    timezone: "EST5EDT"
  open-pull-requests-limit: 2
  reviewers:
    - glotzerlab/signac-maintainers
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: main
  schedule:
    interval: "weekly"
    time: "07:00"
    timezone: "EST5EDT"
  pull-request-branch-name:
    separator: "-"
  reviewers:
    - glotzerlab/signac-maintainers
  open-pull-requests-limit: 2
