version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: main
  schedule:
    interval: "cron"
    cronjob: "9 12 1-7 2,5,8,11 4"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 2
  reviewers:
  - joaander
  groups:
    actions-version:
      applies-to: version-updates
      patterns:
      - '*'
    actions-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: "pip"
  directory: "/"
  target-branch: main
  schedule:
    interval: "cron"
    cronjob: "9 12 1-7 2,5,8,11 4"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 2
  reviewers:
  - joaander
  groups:
    pip-version:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    pip-security:
      applies-to: security-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
