version: 2
build:
    os: ubuntu-20.04
    tools:
        python: "3"
python:
    install:
        - requirements: doc/requirements.txt
        - requirements: requirements.txt
        - path: .
submodules:
    include: all
    recursive: true
