name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test-sdist-and-wheels:
    uses: ./.github/workflows/publish-packages.yml
    with:
      upload_to_test: false
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
