name: Run Unit Tests

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to main
  push:
    branches:
      - 'main'

  # trigger on request
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    name: test (${{ matrix.os }}, ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        python: ['3.10', '3.11', '3.12', '3.13', '3.14']
        # Unused key to force creation of new entries in the matrix
        default: ['true']
        include:
          - os: 'macos-14'
            python: '3.14'
          - os: 'windows-2025'
            python: '3.14'
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@00c67cb577c36bdc2570845fc62d1a30e3383012 # 0.14.0
      with:
        lockfile: "requirements/requirements-test-all-py${{ matrix.python }}.txt"
    - name: Install the package
      run: |
        uv pip install . --no-build-isolation --no-deps --system -v
    - name: Test with pytest
      run: |
        pytest --cov=signac --cov-config=pyproject.toml --cov-report=xml tests/ -v
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  # This job is used to provide a single requirement for branch merge conditions.
  tests_complete:
    name: Unit test
    if: always()
    needs: [test]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: echo "Done."
